#!/usr/bin/env bash
# configures a new HAproxy as a load balancer

# Install HAproxy on a server
sudo apt-get -y update
sudo apt-get -y install haproxy

# Configure haproxy configuration file to distribute requests using a roundrobin algorithm
server_config=\
"
frontend  muhafiz_frontend
        bind *:80
        mode http
        default_backend muhafiz_backend
backend muhafiz_backend
        balance roundrobin
        server 160182-web-01 54.88.113.40 check
        server 160182-web-02 54.173.211.195 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# Testing the HAproxy configuration file
sudo haproxy -c -f /etc/haproxy/haproxy.cfg

# Restart the Nginx service
sudo service haproxy restart
